### ISSUE TITLE
Recent change in Tables.istable

### ISSUE THREAD

**Issue by quinnj** [JuliaComputing/TableView.jl#16]
Hey, just wanted to drop a note about a recent change to `Tables.istable`; it was originally conservative, then released to be more liberal (basically treating anything iterable as a table), and has now gone back to being conservative (in the 0.2 release). The main thing to note is that while `Tables.istable` is perfectly fine to use, there are a few additional cases can technically be considered tables for which `istable` returns false, like Generators of "Row" objects, or `Vector{Any}` where elements are "Row" objects.

Anyway, like I said, probably doesn't really affect things for you, but just wanted to give a heads up.

**Comment by pfitzseb** [comment]
I'm planning to use
```
    if !Tables.istable(table)
        try
            table = Tables.table(table)
        catch err
            throw(ArgumentError("Argument is not a table."))
        end
    end
```
in the future to catch everything that could be a table or made a table (e.g. Arrays). Does that sound sane?

**Comment by quinnj** [comment]
Here's what I'd suggest: https://github.com/JuliaComputing/TableView.jl/pull/21
