### ISSUE TITLE
Displaying Inf, -Inf, NaN

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaComputing/TableView.jl#22]
Thank for your great work! It would be great if values such as `NaN`, `Inf`, `-Inf` could also be displayed when using showtable.

```
using TableView
using DataFrames
showtable(DataFrame([1 Inf -1 -Inf NaN missing]))
```
![image](https://user-images.githubusercontent.com/12156892/59421944-cbe46380-8dcf-11e9-9ded-e9aebed79bcd.png)

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JuliaComputing/TableView.jl/pull/23.
