### ISSUE TITLE
`showtable` can't be downloaded as markdown for the WebIO not detected 

### ISSUE THREAD

**Issue by nesteiner** [JuliaComputing/TableView.jl#56]
I'm sure when I use `showtable`, it has no error at all, but when print preview, it likes this
![2020-07-22 16-37-54 的屏幕截图](https://user-images.githubusercontent.com/46296608/88155687-fb080e00-cc3a-11ea-923e-0c3a4d953e88.png)

and this is in the nootebook
![2020-07-22 16-47-43 的屏幕截图](https://user-images.githubusercontent.com/46296608/88155774-18d57300-cc3b-11ea-86d0-71f03e7f79ac.png)

**Comment by pfitzseb** [comment]
Sorry, I don't understand how those screenshots relate to one another. TableView seems to be working fine in the second one?

**Comment by SteffenPL** [comment]
In the first cell you have `using TableViews` instead of `using TableView`. Maybe that the error.

**Comment by nesteiner** [comment]
> Sorry, I don't understand how those screenshots relate to one another. TableView seems to be working fine in the second one?

yes,
the first one is print preview, it doesn't work at all
the second one is in notebook, it works

**Comment by nesteiner** [comment]
> In the first cell you have `using TableViews` instead of `using TableView`. Maybe that the error.

I don't think so, cause I create a new cell to run it, it still doesn't work

**Comment by SteffenPL** [comment]
Ah, so it works in a jupyter notebook, but not in jupyter lab.

Maybe this helps?
```
using WebIO, IJulia
WebIO.install_jupyter_labextension()
```

Source: https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/#Fixing-Things-Up-1

**Comment by nesteiner** [comment]
> Ah, so it works in a jupyter notebook, but not in jupyter lab.
> 
> Maybe this helps?
> 
> ```
> using WebIO, IJulia
> WebIO.install_jupyter_labextension()
> ```
> 
> Source: https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/#Fixing-Things-Up-1
nope. I mean that it works in notebook, but when I am going to download this ipynb file as markdown or html, it will fail

**Comment by nesteiner** [comment]
> Ah, so it works in a jupyter notebook, but not in jupyter lab.
> 
> Maybe this helps?
> 
> ```
> using WebIO, IJulia
> WebIO.install_jupyter_labextension()
> ```
> 
> Source: https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/#Fixing-Things-Up-1

finally, I can create gif file!! maybe this will be helpful
![y](https://user-images.githubusercontent.com/46296608/88447227-6cc2a080-ce63-11ea-9c69-34bf94786620.gif)

**Comment by nesteiner** [comment]
> > Ah, so it works in a jupyter notebook, but not in jupyter lab.
> > Maybe this helps?
> > ```
> > using WebIO, IJulia
> > WebIO.install_jupyter_labextension()
> > ```
> > 
> > 
> > Source: https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/#Fixing-Things-Up-1
> 
> finally, I can create gif file!! maybe this will be helpful @SteffenPL 
> ![y](https://user-images.githubusercontent.com/46296608/88447227-6cc2a080-ce63-11ea-9c69-34bf94786620.gif)

**Comment by bicepjai** [comment]
I am using `jupyterlab 2.1.0` and the issue i see seems to be related to (this webIO issue)[https://github.com/JuliaGizmos/WebIO.jl/issues/424]

```
An error occured.
ValueError: No linked package for @webio/webio
See the log file for details:  /var/folders/cs/zqcrztp90zn854vddnfrpr940000gp/T/jupyterlab-debug-17xqdxuh.log
No labextension named "@webio/jupyter-lab-provider" installed
An error occured.
ValueError: 
"@webio/jupyter-lab-provider@0.8.14" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.0.2 <2.1.0          >=1.0.1 <2.0.0 @jupyterlab/application
>=2.0.2 <2.1.0          >=1.0.1 <2.0.0 @jupyterlab/docmanager
>=2.0.2 <2.1.0          >=1.0.1 <2.0.0 @jupyterlab/notebook
>=2.0.2 <2.1.0          >=1.0.1 <2.0.0 @jupyterlab/rendermime
>=5.0.2 <5.1.0          >=4.0.1 <5.0.0 @jupyterlab/services
```

**Comment by nesteiner** [comment]
@bicepjai it seeems to be not fixed, do you know when it can be fixed?? 
I have been waiting for a long time :yum:
