### ISSUE TITLE
Better Control of Columns Definitions and other table properties

### ISSUE THREAD

**Issue by galran** [JuliaComputing/TableView.jl#74]
Hi. I just started to use Blink to create some simple UI, in which a user will need to update a small (up to a few hundreds) lines of a DataFrame. TableView seems to offer a very nice solution to this problem, so thank you! 😊

I would like to have some more control over the table definitions, such as disable sorting or removing some columns from the display.

Currently I overridden the “_showtable_sync” function and updadet the “coldefs” argument, but it seems like a hacky solution and will probably break with future updates.

As I’m new to Julia and OpenSource development and etiquette, I was wondering what is the best way to implement such a feature? The solution I thought of is to allow the user to call TableView with the options argument that contains a special key for a callback function that will be called (if exists) just before calling showfun. This callback will accept the options Dict, as it currently contains all the information (including the handlers) and will make the necessary changes. The change itself should be a few lines of code.

Any thoughts?

**Comment by pfitzseb** [comment]
> The solution I thought of is to allow the user to call TableView with the options argument that contains a special key for a callback function that will be called (if exists) just before calling showfun. This callback will accept the options Dict, as it currently contains all the information (including the handlers) and will make the necessary changes. The change itself should be a few lines of code.

That makes sense to me. The other option would be to factor out a `make_options(table_like)` function and then call
```
showtable(table, modify_options(make_options(table))`
```
but the additional complexity that introduces makes me like your idea better. Would be happy to merge a PR for that!

**Comment by galran** [comment]
created a PR. this is my first PR across forks in GitHub so i hope i did it correctly.
