### ISSUE TITLE
Copy and paste multiple cells

### ISSUE THREAD

**Issue by pdeffebach** [JuliaComputing/TableView.jl#80]
A user on [discourse](https://discourse.julialang.org/t/floatingtableview-jl-has-been-submitted-for-registration/44941/9?u=pdeffebach) requested the ability to copy and paste multiple cells. 

Looking at the [docs](https://www.ag-grid.com/javascript-grid/clipboard/) for ag-grid, this looks like it should be feasible. I tried passing more options via a `Dict` (thanks to 0.7!) but I couldn't get it working. Maybe you can try and achieve more success?

**Comment by pfitzseb** [comment]
That's an enterprise only feature, unfortunately. So users can set that themselves when using an enterprise key, but we can't really make it a default.
