### ISSUE TITLE
support for hierarchical (tree / nested) data

### ISSUE THREAD

**Issue by goretkin** [JuliaComputing/TableView.jl#84]
ag-grid can display hierarchical data https://www.ag-grid.com/javascript-grid/tree-data/
Is it within the scope of the TableView.jl package to support hierarchical data?

**Comment by pfitzseb** [comment]
I'd like to support hierarchical data, but unfortunately that's an enterprise-only feature...

**Comment by goretkin** [comment]
Ah, what a shame! Thanks for letting me know.
